const express = require('express')
const app = express()

app.get('/', (req, res) => res.send("FUCKING NORMIES GET THE FUCK OFF MY BOARD. REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"))

app.listen(3000, () => console.log("Chip8 App listening on port 3000!"))
